eureka:
  client:
    serviceUrl:
       defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
     preferIpAddress: true  
spring:
   datasource:
     url: jdbc:mysql://localhost:3306/db_test
     username: root
     password: root
     driver-class: com.mysql.cj.jdbc.Driver
   jpa:
     database-platform: org.hibernate.dialect.MySQLDialect
     hibernate:
       ddl-auto: update
